//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUUOI_DUNG
    {
        public int userid { get; set; }
        public string tai_khoan { get; set; }
        public string mat_khau { get; set; }
        public string so_dien_thoai { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public string avartar { get; set; }
    }
}
